### PR TITLE
[Basic backend] improvements

### PR DESCRIPTION
**Pull request by stephpy**
Fix basic cipher hash, and return error when bad passphrase &| key sent from basic backend.

### CODE REVIEW

**Comment by shouze** [comment]
LGTM

**Comment by stephpy** [comment]
Thanks ;)

**Comment by stephpy** [comment]
Could you tag a 1.0.1 version please ? :)

**Comment by shouze** [comment]
Yes, je sais tagger ;)

**Comment by stephpy** [comment]
Tu aimes tagger ?

**Comment by shouze** [comment]
Yup: https://github.com/rezzza/vaultage/releases/tag/1.0.1

**Pull request merged**
